name:                yuka-project
version:             0.1.0.0
github:              "githubuser/yuka-project"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/yuka-project#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch-tools
- hasktorch
- random
- containers
- gnuplot
- matplotlib
- cassava
- vector
- bytestring
- nlp-tools
- utf8-string

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
    - src
    - Session3

executables:
  yuka-project-exe:
    main:                exercise_5.hs
    source-dirs:         Session2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yuka-project

  Session3-linear-regression:
    main:                LinearRegression.hs
    source-dirs:         Session3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yuka-project
  
  Session3-f:
    main:                Main.hs
    source-dirs:
    - app
    - Session3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yuka-project
  
  session-3-graduate-admission-linear:
    main:                GraduateAdmissionLinear.hs
    source-dirs:
    - Session3
    ghc-options:
    - -main-is GraduateAdmissionLinear
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yuka-project

  Session4-perceptron:
    main:                PerceptronAndGate.hs
    source-dirs:         Session4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yuka-project

  Session4-mlp:
    main:                MlpXor.hs
    source-dirs:         Session4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is MlpXor
    dependencies:
    - yuka-project

  Session5-evaluation:
    main:                Evaluation.hs
    source-dirs:         Session5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Evaluation
    dependencies:
    - yuka-project

  Session5-admit:
    main:                Admit.hs
    source-dirs:         Session5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Admit
    dependencies:
    - yuka-project

  Session5-titanic:
    main:                Titanic.hs
    source-dirs:         Session5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Titanic
    dependencies:
    - yuka-project

  Session6-word2vec:
    main:                Word2Vec.hs
    source-dirs:         Session6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Word2Vec
    dependencies:
    - yuka-project

tests:
  yuka-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yuka-project
